# Generated by Django 6.1.1 on 2026-09-03 08:53

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0018_delete_publicholiday"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="",
                help_text="Planned work belonging to this milestone is shown in this color instead of the color of its service type.",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="color",
            ),
        ),
    ]
