# Generated by Django 6.1.1 on 2026-09-03 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0032_auto_20260519_0936"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="budget_alert_at",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The contact person receives a mail once. Useful when you agreed with the customer to get in touch before the cost cap is used up.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="send a mail when the logged cost reaches",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="budget_alert_sent_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="budget alert sent at",
            ),
        ),
    ]
