# Generated by Django 6.1.1 on 2026-09-03 09:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0033_project_budget_alert_at_project_budget_alert_sent_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetTransfer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="amount",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "from_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_transfers_out",
                        to="projects.project",
                        verbose_name="from project",
                    ),
                ),
                (
                    "to_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave this empty to only reserve the budget for now. It stops counting towards the source project either way.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_transfers_in",
                        to="projects.project",
                        verbose_name="to project",
                    ),
                ),
            ],
            options={
                "verbose_name": "budget transfer",
                "verbose_name_plural": "budget transfers",
                "ordering": ["-created_at"],
            },
        ),
    ]
