# Generated by Django 6.1.1 on 2026-09-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0027_invoice_archived_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="postpone_reminders_until",
            field=models.DateField(
                blank=True,
                help_text="The invoice is left out of the reminders list until this date, for example while a question of the customer is being clarified.",
                null=True,
                verbose_name="postpone reminders until",
            ),
        ),
    ]
